#!/usr/bin/env python3
"""Download and self-host the two site typefaces as woff2 subsets.

The site makes no call to a font CDN, so the files have to live in
``static/fonts/``. This script puts them there. Edit this file, never the
generated ``static/fonts/fonts.css``.

Two faces, three roles:

* **Archivo** — display and utility. Headings, the margin column, dates, tags.
* **Spectral** — body. Reading text.

Each face is fetched twice, once for the Latin block and once for Latin
Extended. The split is load-bearing rather than decorative: Latin Extended is
where ``ő ű Ő Ű`` live, and this site is written in Hungarian, so the ``-ext``
files are the ones that carry most of the running text's accents. Both faces
were checked to draw a real double acute — two slanted strokes, matching the
angle of their own single acute — and not a repurposed dieresis. A font that
fails that check is unusable here no matter how well it covers the codepoints.

Both faces are under the SIL Open Font License 1.1; the licence text is
downloaded alongside them.

Usage::

    python3 scripts/fetch_fonts.py
"""

from __future__ import annotations

import hashlib
import re
import sys
import urllib.request
from pathlib import Path

FONTS_DIR = Path(__file__).resolve().parent.parent / "static" / "fonts"

# Google serves a different set of @font-face blocks depending on what the
# requesting browser is understood to support. Asking as a current Chrome is
# what gets woff2 with a unicode-range split rather than a single fat file.
UA = (
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# (family, css2 axis spec, roles the weights serve — the last is documentation only)
FACES = [
    ("Archivo", "wght@500;700", "display, utility"),
    ("Spectral", "ital,wght@0,400;0,600;1,400", "body, body italic, body emphasis"),
]

# Only these two subsets are kept. The faces also ship Cyrillic, Greek and
# Vietnamese; none of them are wanted, and shipping them would triple the
# download for text that will never contain them.
WANTED_SUBSETS = ("latin", "latin-ext")

LICENCES = {
    "archivo": "https://raw.githubusercontent.com/google/fonts/main/ofl/archivo/OFL.txt",
    "spectral": "https://raw.githubusercontent.com/google/fonts/main/ofl/spectral/OFL.txt",
}


def get(url: str, binary: bool = False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as resp:
        raw = resp.read()
    return raw if binary else raw.decode("utf-8")


def parse_css(css: str):
    """Yield one dict per @font-face block, tagged with its preceding subset comment.

    Google emits ``/* latin-ext */`` immediately above the block it describes.
    That comment is the only machine-readable marker of which subset a block
    covers, so the blocks are split on it rather than parsed as real CSS.
    """
    parts = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    # parts == ['', subset, block, subset, block, ...]
    for subset, block in zip(parts[1::2], parts[2::2]):
        url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
        weight = re.search(r"font-weight:\s*([^;]+);", block)
        style = re.search(r"font-style:\s*([^;]+);", block)
        urange = re.search(r"unicode-range:\s*([^;]+);", block)
        if not (url and weight and style and urange):
            continue
        yield {
            "subset": subset,
            "url": url.group(1),
            "weight": weight.group(1).strip(),
            "style": style.group(1).strip(),
            "range": urange.group(1).strip(),
        }


def main() -> int:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css_out = [
        "/* Self-hosted woff2 subsets, Latin and Latin Extended.",
        " * Generated by scripts/fetch_fonts.py — edit that, not this.",
        " *",
        " * Archivo and Spectral are both under the SIL Open Font License 1.1;",
        " * see OFL-archivo.txt and OFL-spectral.txt beside this file.",
        " *",
        " * The -ext files carry the Hungarian o- and u-double-acute. On a site",
        " * written in Hungarian they are not an optional extra, which is why they",
        " * are preloaded alongside the Latin ones rather than left to be",
        " * discovered when the first accented word is painted.",
        " */",
        "",
    ]

    for family, axis, _roles in FACES:
        css = get(f"https://fonts.googleapis.com/css2?family={family.replace(' ', '+')}:{axis}&display=swap")
        blocks = [b for b in parse_css(css) if b["subset"] in WANTED_SUBSETS]
        if not blocks:
            print(f"error: no usable @font-face blocks for {family}", file=sys.stderr)
            return 1

        # Asking for two weights of a variable family gets the same variable file
        # back twice, once per weight, differing only in the declared
        # `font-weight`. Writing both would ship the identical bytes under two
        # names and double the download for nothing. Group by what the bytes
        # actually are, and collapse a group into a single file declaring the
        # weight *range* it covers — which is the honest declaration for a
        # variable font anyway.
        groups: dict[tuple, dict] = {}
        for block in blocks:
            payload = get(block["url"], binary=True)
            key = (block["style"], block["subset"], hashlib.md5(payload).hexdigest())
            g = groups.setdefault(
                key, {"payload": payload, "weights": set(), "range": block["range"]}
            )
            # A block may already declare a range ("500 700"); take both ends.
            g["weights"].update(int(w) for w in block["weight"].split())

        for (style, subset, _digest), g in groups.items():
            lo, hi = min(g["weights"]), max(g["weights"])
            weight_css = str(lo) if lo == hi else f"{lo} {hi}"
            weight_name = str(lo) if lo == hi else f"{lo}-{hi}"
            sub = "ext" if subset == "latin-ext" else "lat"
            stem = f"{family.lower().replace(' ', '')}-{weight_name}-{'i' if style == 'italic' else 'n'}-{sub}"
            path = FONTS_DIR / f"{stem}.woff2"

            path.write_bytes(g["payload"])
            print(f"  {path.name:<32} {path.stat().st_size:>7,} bytes  [{subset}]")

            css_out += [
                "@font-face {",
                f"  font-family: '{family}';",
                f"  font-style: {style};",
                f"  font-weight: {weight_css};",
                "  font-display: swap;",
                f"  src: url('./{path.name}') format('woff2');",
                f"  unicode-range: {g['range']};",
                "}",
                "",
            ]

    for name, url in LICENCES.items():
        (FONTS_DIR / f"OFL-{name}.txt").write_text(get(url), encoding="utf-8")
        print(f"  OFL-{name}.txt")

    (FONTS_DIR / "fonts.css").write_text("\n".join(css_out), encoding="utf-8")
    print(f"\nwrote {FONTS_DIR / 'fonts.css'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
