#!/usr/bin/env python3
"""Fetch the title and thumbnail for every YouTube video a post embeds.

The site has no JavaScript and no iframes, so a video is shown as a poster: its
own thumbnail, stored here, above a link to YouTube. Nothing is requested from
Google when a reader opens the page, which is what keeps the consent banner
honest — an embedded player would set cookies before anyone had agreed to
anything.

Scans content/ for ``{{< youtube ID >}}``, asks YouTube's oEmbed endpoint for
the title, saves the thumbnail under static/img/youtube/, and writes
data/youtube.yaml for the shortcode to read. Already-fetched videos are skipped,
so this is cheap to re-run.

Usage::

    python3 scripts/fetch_youtube.py [--force]
"""

from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
THUMBS = ROOT / "static" / "img" / "youtube"
DATA = ROOT / "data" / "youtube.yaml"

OEMBED = "https://www.youtube.com/oembed"
TIMEOUT = 20

#: Matches the shortcode in either form: a bare id or id="...".
SHORTCODE = re.compile(r'\{\{<\s*youtube\s+(?:id=")?([A-Za-z0-9_-]{6,20})"?[^>]*>}}')


def video_ids() -> list[str]:
    """Every video id referenced by a shortcode, in first-seen order."""
    seen: dict[str, None] = {}
    for path in sorted(CONTENT.rglob("*.md")):
        for match in SHORTCODE.finditer(path.read_text(encoding="utf-8")):
            seen.setdefault(match.group(1), None)
    return list(seen)


def oembed(video_id: str) -> dict[str, str] | None:
    """Ask YouTube for a video's title and thumbnail.

    Returns None when the video is gone. A removed video still answers 200 on
    its watch page, so oEmbed is the only reliable liveness check — the same
    reason the media list uses it.
    """
    url = f"https://www.youtube.com/watch?v={video_id}"
    query = urllib.parse.urlencode({"url": url, "format": "json"})
    try:
        with urllib.request.urlopen(f"{OEMBED}?{query}", timeout=TIMEOUT) as response:
            return json.loads(response.read().decode("utf-8"))
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
        return None


def save_thumbnail(video_id: str, url: str) -> str | None:
    """Download a thumbnail next to the site's other images."""
    THUMBS.mkdir(parents=True, exist_ok=True)
    target = THUMBS / f"{video_id}.jpg"
    try:
        with urllib.request.urlopen(url, timeout=TIMEOUT) as response:
            if not response.headers.get("Content-Type", "").startswith("image/"):
                return None
            target.write_bytes(response.read())
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError):
        return None
    return f"/img/youtube/{video_id}.jpg"


def quote(value: str) -> str:
    """Render a string as a double-quoted YAML scalar."""
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    """Fetch what is missing and rewrite the data file."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="refetch everything")
    args = parser.parse_args()

    ids = video_ids()
    if not ids:
        print("no {{< youtube >}} shortcodes in content/ — nothing to do.")
        return 0

    known: dict[str, dict[str, str]] = {}
    if DATA.exists() and not args.force:
        current = None
        for line in DATA.read_text(encoding="utf-8").splitlines():
            if line and not line.startswith((" ", "#")):
                current = line.rstrip(":").strip('"')
                known[current] = {}
            elif current and ":" in line:
                key, _, value = line.strip().partition(":")
                known[current][key] = value.strip().strip('"')

    missing = 0
    for video_id in ids:
        if video_id in known and known[video_id].get("cim"):
            continue
        info = oembed(video_id)
        if info is None:
            print(f"  {video_id}: not available — left for the shortcode to link")
            known[video_id] = {"allapot": "hianyzik"}
            missing += 1
            continue
        thumb = save_thumbnail(video_id, info.get("thumbnail_url", ""))
        known[video_id] = {
            "cim": info.get("title", ""),
            "szerzo": info.get("author_name", ""),
            "kep": thumb or "",
            "allapot": "ok",
        }
        print(f"  {video_id}: {info.get('title', '')[:60]}")

    lines = [
        "# Generated by scripts/fetch_youtube.py — do not edit by hand.",
        "# Titles and thumbnails for the videos the posts show as posters.",
    ]
    for video_id in sorted(known):
        lines.append(f"{quote(video_id)}:")
        for key, value in sorted(known[video_id].items()):
            if value:
                lines.append(f"  {key}: {quote(value)}")
    DATA.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {DATA.relative_to(ROOT)} — {len(known)} video(s), {missing} unavailable")
    return 0


if __name__ == "__main__":
    sys.exit(main())
